-- AlterTable
ALTER TABLE `Participant` ADD COLUMN `lastUpdateBy` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Receipt` ADD COLUMN `lastUpdateBy` VARCHAR(191) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
